function exportTGMMConfigFile( dataStr )
mkdir( 'AutoTGMMConfig\' );
fileName = strcat( 'AutoTGMMConfig\TGMM_configFile', dataStr, '.txt' );
fileID = fopen( char(fileName), 'w' );
fprintf( fileID, '%s\n', 'imgFilePattern=I:\FrankfurtLSFMDatasets\20121211_pGATA_H2B_Wave\3Ddrift_Stacks_cropped\cropped_t???_c1' );
output = strcat( 'debugPathPrefix=I:\SegmentationResults\TGMM\', dataStr );
fprintf( fileID, '%s\n', char(output) );
fprintf( fileID, '%s\n', 'anisotropyZ=2.0' );
fprintf( fileID, '%s\n', 'backgroundThreshold=800' );
fprintf( fileID, '%s\n', 'persistanceSegmentationTau=600' );
fprintf( fileID, '%s\n', 'betaPercentageOfN_k=1.0' );
fprintf( fileID, '%s\n', 'nuPercentageOfN_k=1.0' );
fprintf( fileID, '%s\n', 'alphaPercentage=5.0' );
fprintf( fileID, '%s\n', 'maxIterEM=100' );
fprintf( fileID, '%s\n', 'tolLikelihood=1e-6' );
fprintf( fileID, '%s\n', 'regularizePrecisionMatrixConstants_lambdaMin=0.002' );
fprintf( fileID, '%s\n', 'regularizePrecisionMatrixConstants_lambdaMax=5.0' );
fprintf( fileID, '%s\n', 'regularizePrecisionMatrixConstants_maxExcentricity=100.0' );
fprintf( fileID, '%s\n', 'temporalWindowForLogicalRules=5' );
fprintf( fileID, '%s\n', 'thrBackgroundDetectorHigh=0.8' );
fprintf( fileID, '%s\n', 'thrBackgroundDetectorLow=0.2' );
fprintf( fileID, '%s\n', 'SLD_lengthTMthr=5' );
fprintf( fileID, '%s\n', 'radiusMedianFilter=2' );
fprintf( fileID, '%s\n', 'minTau=2' );
fprintf( fileID, '%s\n', 'conn3D=74' );
fprintf( fileID, '%s\n', 'estimateOpticalFlow=0' );
fprintf( fileID, '%s\n', 'maxDistPartitionNeigh=80.0' );
fprintf( fileID, '%s\n', 'deathThrOpticalFlow=-1' );
fprintf( fileID, '%s\n', 'minNucleiSize=25' );
fprintf( fileID, '%s\n', 'maxNucleiSize=6000' );
fprintf( fileID, '%s\n', 'maxPercentileTrimSV=0.4' );
fprintf( fileID, '%s\n', 'conn3DsvTrim=6' );
fprintf( fileID, '%s\n', 'maxNumKNNsupervoxel=10' );
fprintf( fileID, '%s\n', 'maxDistKNNsupervoxel=41.0' );
fprintf( fileID, '%s\n', 'thrSplitScore=-1.0' );
fprintf( fileID, '%s\n', 'thrCellDivisionPlaneDistance=3.2' );
fprintf( fileID, '%s\n', 'thrCellDivisionWithTemporalWindow=0.3' );
fclose( fileID );
