#!/bin/bash
shopt -s nullglob
cd ..
cd images
#delete redundant images
#declare count=0
#for f in *.jpg
#do
#	if ((count > 499))
#	then
#		echo $f
#		rm -rf $f
#	fi
#	((count++))
#done

#create movies
# NH
NAME1="Model${NAME}_NH_C.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-NH_C%04d.jpg -vframes 500 -vcodec libx264 tempNHC.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i tempNHC.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME1}

NAME2="Model${NAME}_NH_S.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-NH_S%04d.jpg -vframes 500 -vcodec libx264 tempNHS.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i tempNHS.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME2}

NAME3="Model${NAME}_NH_L.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-NH_L%04d.jpg -vframes 500 -vcodec libx264 tempNHL.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i tempNHL.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME3}

# 1DC
NAME4="Model${NAME}_1DC_C.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-1DC_C%04d.jpg -vframes 500 -vcodec libx264 temp1DCC.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp1DCC.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME4}

NAME5="Model${NAME}_1DC_S.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-1DC_S%04d.jpg -vframes 500 -vcodec libx264 temp1DCS.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp1DCS.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME5}

NAME6="Model${NAME}_1DC_L.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-1DC_L%04d.jpg -vframes 500 -vcodec libx264 temp1DCL.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp1DCL.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME6}

# 2DC
NAME7="Model${NAME}_2DC_C.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-2DC_C%04d.jpg -vframes 500 -vcodec libx264 temp2DCC.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp2DCC.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME7}

NAME8="Model${NAME}_2DC_S.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-2DC_S%04d.jpg -vframes 500 -vcodec libx264 temp2DCS.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp2DCS.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME8}

NAME9="Model${NAME}_2DC_L.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-2DC_L%04d.jpg -vframes 500 -vcodec libx264 temp2DCL.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp2DCL.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME9}

# 2DCBase
NAME10="Model${NAME}_2DCBase_C.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-2DCBase_C%04d.jpg -vframes 500 -vcodec libx264 temp2DCBaseC.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp2DCBaseC.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME10}

NAME11="Model${NAME}_2DCBase_S.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-2DCBase_S%04d.jpg -vframes 500 -vcodec libx264 temp2DCBaseS.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp2DCBaseS.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME11}

NAME12="Model${NAME}_2DCBase_L.avi"
~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -framerate 24 -i m-2DCBase_L%04d.jpg -vframes 500 -vcodec libx264 temp2DCBaseL.avi && ~/Tools/ffmpeg-2.0.1-64bit-static/./ffmpeg -i temp2DCBaseL.avi -filter:v "crop=iw:350:0:500" -vcodec libx264 ${NAME12}

rm -rf temp*.avi
FOLDER="/home/necrolyte/Uni/LateralRootGrowth/300615/GrowthInHeightOnly/"
mv ${NAME1} $FOLDER
mv ${NAME2} $FOLDER
mv ${NAME3} $FOLDER
mv ${NAME4} $FOLDER
mv ${NAME5} $FOLDER
mv ${NAME6} $FOLDER
mv ${NAME7} $FOLDER
mv ${NAME8} $FOLDER
mv ${NAME9} $FOLDER
mv ${NAME10} $FOLDER
mv ${NAME11} $FOLDER
mv ${NAME12} $FOLDER
